### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by Exotikcheatt** [Brendanj9554/MWIII-dma-base#2]
a lot thing not here man continues vector , Globals and others fucking shit

**Comment by Brendanj9554** [comment]
I notice you have a dma base from Dec23. Rather than complain that everything isn't done for you use the functions that are available in my git and (update) and add to the base you have already copied and renamed as your own? Just a thought. Also please read the git.... this is for serous people to collaborate on. Not a free lunch for a P2C. This isn't what I would consider an issue so I will close it

**Comment by Brendanj9554** [comment]
Wanna be P2C provider complaining about not being able to rip off other people's work and make money for it. Evidence is clear looking at his repo and the original sources
